AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 instance for Ansible + NGINX setup

Resources:
  AnsibleEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c7217cdde317cfec  # Ubuntu 22.04 LTS (us-east-1)
      KeyName: aws-keypair.pem          # Replace with your key pair
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: AnsibleTest
      UserData:
        Fn::Base64: |
          #!/bin/bash
          apt-get update
          apt-get install -y python3

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

